CREATE DATABASE OnlineBookstore;
use OnlineBookStore;
DROP TABLE IF EXISTS Books;

CREATE TABLE books (
	Book_ID SERIAL PRIMARY KEY,
    Title VARCHAR(100),
    Author VARCHAR(100),
    Genre VARCHAR(50),
    Published_Year INT,
    Price NUMERIC(10,2),
    Stock INT
);


DROP TABLE IF EXISTS Customers;
CREATE TABLE customers(
	Customer_ID SERIAL PRIMARY KEY,
    Name VARCHAR(100),
    Email VARCHAR(100),
    Phone VARCHAR(15),
    City VARCHAR(50),
    Country VARCHAR(150)
);


DROP TABLE IF EXISTS Orders;
CREATE TABLE orders(
	Order_ID SERIAL PRIMARY KEY,
    Customer_ID INT,
    Book_ID INT,
    Order_date DATE,
    Quantity INT,
    Total_Amount NUMERIC(10,2),
    FOREIGN KEY (Customer_ID) REFERENCES customers(Customer_ID),
    FOREIGN KEY(Book_ID) REFERENCES books(Book_ID)
);

select * from books;

Select * from customers;

Select * from Orders;


-- Retreive all Books in the "Fiction" Genre:

select * from books
where Genre='Fiction';

-- Find Books published after the year 1950:

select * from books
where Published_Year>1950;


-- Show orders placed in November 2023:

select * from orders
where order_date between '2023-11-1' AND '2023-11-30';


-- Retrieve the total stock of books available:

Select sum(stock) as Total_Stock
from books;

-- Find the details of most expensive book:

select * from books
order by price DESC
LIMIT 1;

-- Show all Customers Who ordered more than 1 quantity of a book:

select * from orders
where Quantity>1;

-- Retrieve all orders where the total amount is greater than 20, 
-- sort them by total amount in ascending order,skip the first 20 records, 
-- and display the next 100 records.

select * from orders
where Total_Amount >20
order by Total_Amount 
Limit 100
offset 20;


-- Retrieve the details of the book(s) having the lowest stock available in the inventory.

select * from books
where Stock = (select MIN(Stock) from books);


-- Retrieve the total number of books sold for each genre:

Select b.Genre, SUM(o.Quantity) as Total_Books_Sold
from orders o
Join Books b ON o.book_id=b.book_id
Group by b.Genre;

-- Find the Average Price of books in the 'Fantasy' Genre:

SELECT AVG(Price) AS Average_Price
FROM books
WHERE Genre = 'Fantasy';


-- List customers Who have placed at least 2 orders:

select o.Customer_ID, c.name, COUNT(o.Order_ID) AS Order_Count
from orders o
JOIN customers c ON o.Customer_id=c.customer_id
group by o.customer_id, c.name
having Count(order_id)>=2;


-- Find the Most Frequently Ordered Book:

select o.Book_Id, b.Title, Count(o.Order_ID) AS Order_count
FROM orders o
JOIN books b ON o.book_Id = b.book_Id
Group By o.Book_Id, b.Title
order by Order_count Desc 
Limit 1;

-- Show the top 3 Most Expensive books of 'Fantasy' Genre:

Select * from books
Where Genre = 'Fantasy'
Order by Price Desc
Limit 3;


-- Retrieve the total Quantity of Books sold by Each author:

Select b.author, Sum(o.quantity) as Total_Books_Sold
From orders o
Join books b on o.book_Id = b.Book_Id
Group by b.author;


-- List the Cities where customers who Spent over Rs 30 are loacted:

Select distinct c.city, Total_Amount
from orders o
Join customers c ON o.customer_id = c.customer_Id
Where o.Total_Amount >30
order by Total_Amount ASC;


-- Find the Customer Who spent the most on orders:

select c.customer_id, c.name, Sum(o.Total_Amount) as Total_Spent
from orders o
Join customers c ON o.customer_Id = c.customer_Id
Group by c.customer_id, c.name
order by Total_Spent Desc
Limit 1;


-- calculate the stock remaining after fulfilling all orders:

SELECT b.title,
       b.stock,
       SUM(o.quantity) AS Sold,
       b.stock - SUM(o.quantity) AS Remaining
FROM books b
JOIN orders o
ON b.book_id = o.book_id
GROUP BY b.title, b.stock;

-- Monthly Sales Report

SELECT 
    DATE_FORMAT(order_date, '%M %Y') AS Month,
    SUM(Total_Amount) AS Total_Sales
FROM orders
GROUP BY YEAR(order_date), MONTH(order_date), DATE_FORMAT(order_date, '%M %Y')
ORDER BY YEAR(order_date), MONTH(order_date);


-- Top Selling Genre

Select b.genre,
Sum(o.quantity) as Total_Sold
From orders o
Join books b ON o.book_Id = b.book_Id
Group by b.genre
Order by Total_Sold Desc
Limit 1;

-- Customers Who Never Ordered

Select c.customer_Id, c.name
From customers c
Left Join orders o ON c.customer_Id = o.customer_Id
where o.order_Id is NULL;

-- Revenue Generated By each book

select b.Title, sum(o.total_amount) as Revenue
From orders o
Join books b ON o.book_id = b.book_Id
group by b.Title
Order by Revenue Desc;


-- Low Stock Alert

Select Title, Stock
from books
where Stock < 5
order by Stock ASC;

-- Best Customer Per City

select c.city, c.name,
SUM(o.Total_Amount) AS Total_Spent
From customers c
Join orders o ON c.customer_Id = o.customer_Id
Group by c.city,c.name
Order By Total_spent Desc;


-- Most Valuable Customer

Select c.name, Sum(o.Total_Amount) as Lifetime_Value
from customers c
Join orders o ON c.customer_Id = o.customer_Id
Group by c.name
Order by Lifetime_Value Desc
Limit 5;






